# Pandas 30 个基础核心功能演示

本 notebook 通过两个精简的虚构数据集，系统演示 pandas 最常用的 30 个核心功能，
覆盖**数据查看、选择、筛选、清洗、转换、聚合、合并、透视**等日常分析全流程。

- **数据集 1 `employees`**：员工信息表（含部门、年龄、薪资、入职日期等，故意留了缺失值）
- **数据集 2 `sales`**：销售订单表（可与员工表通过 `emp_id` 关联）

> 运行方式：从上到下依次执行（Shift+Enter）。每个小节标题即对应的 pandas 功能点。

## 0. 准备：导入库 & 构造虚构数据集

In [1]:
import pandas as pd
import numpy as np

print("pandas 版本:", pd.__version__)

pandas 版本: 2.2.3

In [2]:
# 数据集 1：员工信息表（department / salary 故意留有缺失值 NaN）
employees = pd.DataFrame({
    "emp_id":     [1, 2, 3, 4, 5, 6, 7, 8],
    "name":       ["张伟", "李娜", "王芳", "刘洋", "陈静", "杨磊", "赵敏", "周强"],
    "department": ["研发", "市场", "研发", "销售", "市场", "研发", "销售", np.nan],
    "age":        [29, 34, 41, 28, 45, 31, 38, 26],
    "salary":     [21000, 18000, 27000, 15000, 23000, np.nan, 16000, 14000],
    "hire_date":  ["2019-03-01", "2017-07-15", "2015-01-20", "2020-09-10",
                   "2014-05-30", "2018-11-05", "2016-08-22", "2021-02-14"],
    "city":       ["北京", "上海", "北京", "深圳", "上海", "杭州", "深圳", "北京"],
    "gender":     ["M", "F", "F", "M", "F", "M", "F", "M"],
})

employees

   emp_id name department  age   salary   hire_date city gender
0       1   张伟         研发   29  21000.0  2019-03-01   北京      M
1       2   李娜         市场   34  18000.0  2017-07-15   上海      F
2       3   王芳         研发   41  27000.0  2015-01-20   北京      F
3       4   刘洋         销售   28  15000.0  2020-09-10   深圳      M
4       5   陈静         市场   45  23000.0  2014-05-30   上海      F
5       6   杨磊         研发   31      NaN  2018-11-05   杭州      M
6       7   赵敏         销售   38  16000.0  2016-08-22   深圳      F
7       8   周强        NaN   26  14000.0  2021-02-14   北京      M

In [3]:
# 数据集 2：销售订单表（通过 emp_id 可与员工表关联）
sales = pd.DataFrame({
    "order_id":   range(1001, 1013),
    "emp_id":     [1, 2, 1, 4, 7, 4, 2, 5, 1, 7, 4, 3],
    "product":    ["A", "B", "C", "A", "B", "A", "C", "B", "A", "C", "B", "A"],
    "quantity":   [3, 5, 2, 7, 1, 4, 6, 2, 9, 3, 5, 1],
    "price":      [199, 99, 299, 199, 99, 199, 299, 99, 199, 299, 99, 199],
    "order_date": ["2023-01-05", "2023-01-08", "2023-02-11", "2023-02-15",
                   "2023-03-01", "2023-03-09", "2023-03-20", "2023-04-02",
                   "2023-04-18", "2023-05-05", "2023-05-21", "2023-06-01"],
})

sales

    order_id  emp_id product  quantity  price  order_date
0       1001       1       A         3    199  2023-01-05
1       1002       2       B         5     99  2023-01-08
2       1003       1       C         2    299  2023-02-11
3       1004       4       A         7    199  2023-02-15
4       1005       7       B         1     99  2023-03-01
5       1006       4       A         4    199  2023-03-09
6       1007       2       C         6    299  2023-03-20
7       1008       5       B         2     99  2023-04-02
8       1009       1       A         9    199  2023-04-18
9       1010       7       C         3    299  2023-05-05
10      1011       4       B         5     99  2023-05-21
11      1012       3       A         1    199  2023-06-01

## 1. `head()` / `tail()` / `sample()` — 快速预览数据

查看数据的前几行、后几行或随机抽样，是拿到数据的第一步。

In [4]:
print("前 3 行：")
display(employees.head(3))

print("后 2 行：")
display(employees.tail(2))

print("随机抽样 3 行：")
employees.sample(3, random_state=42)

前 3 行：

   emp_id name department  age   salary   hire_date city gender
0       1   张伟         研发   29  21000.0  2019-03-01   北京      M
1       2   李娜         市场   34  18000.0  2017-07-15   上海      F
2       3   王芳         研发   41  27000.0  2015-01-20   北京      F

后 2 行：

   emp_id name department  age   salary   hire_date city gender
6       7   赵敏         销售   38  16000.0  2016-08-22   深圳      F
7       8   周强        NaN   26  14000.0  2021-02-14   北京      M

随机抽样 3 行：

   emp_id name department  age   salary   hire_date city gender
1       2   李娜         市场   34  18000.0  2017-07-15   上海      F
5       6   杨磊         研发   31      NaN  2018-11-05   杭州      M
0       1   张伟         研发   29  21000.0  2019-03-01   北京      M

## 2. 基本属性 — `shape` / `columns` / `dtypes` / `index`

不需要括号，它们是 DataFrame 的**属性**，用来了解数据的"骨架"。

In [5]:
print("形状 (行, 列):", employees.shape)
print("列名:", list(employees.columns))
print("行数:", len(employees))
print("\n各列数据类型:")
print(employees.dtypes)

形状 (行, 列): (8, 8)
列名: ['emp_id', 'name', 'department', 'age', 'salary', 'hire_date', 'city', 'gender']
行数: 8

各列数据类型:
emp_id          int64
name           object
department     object
age             int64
salary        float64
hire_date      object
city           object
gender         object
dtype: object

## 3. `info()` — 结构概览（类型 + 非空计数 + 内存）

一眼看出哪些列有缺失值、各列类型、整体占用内存。

In [6]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      8 non-null      int64
 1   name        8 non-null      object
 2   department  7 non-null      object
 3   age         8 non-null      int64
 4   salary      7 non-null      float64
 5   hire_date   8 non-null      object
 6   city        8 non-null      object
 7   gender      8 non-null      object
dtypes: float64(1), int64(2), object(5)
memory usage: 644.0+ bytes

## 4. `describe()` — 描述性统计

默认对数值列给出计数、均值、标准差、分位数；加 `include="all"` 可一并描述文本列。

In [7]:
print("数值列描述统计：")
display(employees.describe())

print("全部列（含文本列）：")
employees.describe(include="all")

数值列描述统计：

        emp_id        age        salary
count  8.00000   8.000000      7.000000
mean   4.50000  34.000000  19142.857143
std    2.44949   6.761234   4740.906082
min    1.00000  26.000000  14000.000000
25%    2.75000  28.750000  15500.000000
50%    4.50000  32.500000  18000.000000
75%    6.25000  38.750000  22000.000000
max    8.00000  45.000000  27000.000000

全部列（含文本列）：

,emp_id,name,department,age,salary,hire_date,city,gender
count,8.00000,8,7,8.000000,7.000000,8,8,8
unique,NaN,8,3,NaN,NaN,8,4,2
top,NaN,张伟,研发,NaN,NaN,2019-03-01,北京,M
freq,NaN,1,3,NaN,NaN,1,3,4
mean,4.50000,NaN,NaN,34.000000,19142.857143,NaN,NaN,NaN
std,2.44949,NaN,NaN,6.761234,4740.906082,NaN,NaN,NaN
min,1.00000,NaN,NaN,26.000000,14000.000000,NaN,NaN,NaN
25%,2.75000,NaN,NaN,28.750000,15500.000000,NaN,NaN,NaN
50%,4.50000,NaN,NaN,32.500000,18000.000000,NaN,NaN,NaN
75%,6.25000,NaN,NaN,38.750000,22000.000000,NaN,NaN,NaN
max,8.00000,NaN,NaN,45.000000,27000.000000,NaN,NaN,NaN

## 5. 选择列 — 单列返回 Series，多列返回 DataFrame

In [8]:
# 单列 -> Series
s = employees["name"]
print(type(s).__name__, "→\n", s.head(3), sep="")

# 多列 -> DataFrame（注意双层方括号）
employees[["name", "department", "salary"]].head()

Series→
0    张伟
1    李娜
2    王芳
Name: name, dtype: object

  name department   salary
0   张伟         研发  21000.0
1   李娜         市场  18000.0
2   王芳         研发  27000.0
3   刘洋         销售  15000.0
4   陈静         市场  23000.0

## 6. `loc` — 按**标签**选择行和列

语法：`df.loc[行标签, 列标签]`，区间是**闭区间**（含末端）。

In [9]:
# 第 0~2 行的 name、salary 列
display(employees.loc[0:2, ["name", "salary"]])

# 配合条件：研发部门的姓名与薪资
employees.loc[employees["department"] == "研发", ["name", "salary"]]

  name   salary
0   张伟  21000.0
1   李娜  18000.0
2   王芳  27000.0

  name   salary
0   张伟  21000.0
2   王芳  27000.0
5   杨磊      NaN

## 7. `iloc` — 按**位置**（整数下标）选择

语法：`df.iloc[行位置, 列位置]`，区间是**左闭右开**（同 Python 切片）。

In [10]:
# 前 3 行、前 4 列
display(employees.iloc[0:3, 0:4])

# 取单个值：第 2 行第 1 列
print("employees.iloc[2, 1] =", employees.iloc[2, 1])

   emp_id name department  age
0       1   张伟         研发   29
1       2   李娜         市场   34
2       3   王芳         研发   41

employees.iloc[2, 1] = 王芳

## 8. 布尔条件筛选 — 最常用的"按条件取数据"

In [11]:
# 薪资 > 18000 的员工
high_pay = employees[employees["salary"] > 18000]
high_pay[["name", "salary"]]

  name   salary
0   张伟  21000.0
2   王芳  27000.0
4   陈静  23000.0

## 9. 多条件 & `isin()` / `between()`

多条件用 `&`（与）`|`（或），每个条件必须用括号包起来。

In [12]:
# 年龄在 30~40 之间，且不在北京
mask = employees["age"].between(30, 40) & (employees["city"] != "北京")
display(employees[mask][["name", "age", "city"]])

# isin：城市属于一线城市集合
employees[employees["city"].isin(["北京", "上海"])][["name", "city"]]

  name  age city
1   李娜   34   上海
5   杨磊   31   杭州
6   赵敏   38   深圳

  name city
0   张伟   北京
1   李娜   上海
2   王芳   北京
4   陈静   上海
7   周强   北京

## 10. 新增列 — 直接赋值 / `assign()`

In [13]:
# 直接赋值新增一列：年薪
employees["annual_salary"] = employees["salary"] * 12

# assign 链式新增（返回新对象，不改原表）：是否高级员工
employees = employees.assign(senior=lambda d: d["age"] >= 40)

employees[["name", "salary", "annual_salary", "senior"]]

  name   salary  annual_salary  senior
0   张伟  21000.0       252000.0   False
1   李娜  18000.0       216000.0   False
2   王芳  27000.0       324000.0    True
3   刘洋  15000.0       180000.0   False
4   陈静  23000.0       276000.0    True
5   杨磊      NaN            NaN   False
6   赵敏  16000.0       192000.0   False
7   周强  14000.0       168000.0   False

## 11. `drop()` — 删除列或行

`axis=1` 删列，`axis=0`（默认）删行。

In [14]:
# 删除刚才的辅助列（不改原表，返回副本）
tmp = employees.drop(columns=["annual_salary", "senior"])
print("删列后剩余列：", list(tmp.columns))

# 删除指定行（按索引标签）
print("删行后行数：", employees.drop(index=[0, 1]).shape[0])

删列后剩余列： ['emp_id', 'name', 'department', 'age', 'salary', 'hire_date', 'city', 'gender']
删行后行数： 6

## 12. `rename()` — 重命名列名 / 索引

In [15]:
employees.rename(columns={
    "name": "姓名",
    "department": "部门",
    "salary": "月薪",
}).head(3)

   emp_id  姓名  部门  age       月薪   hire_date city gender  annual_salary  senior
0       1  张伟  研发   29  21000.0  2019-03-01   北京      M       252000.0   False
1       2  李娜  市场   34  18000.0  2017-07-15   上海      F       216000.0   False
2       3  王芳  研发   41  27000.0  2015-01-20   北京      F       324000.0    True

## 13. `sort_values()` — 按值排序

In [16]:
# 按薪资降序；缺失值放最后
employees.sort_values("salary", ascending=False, na_position="last")[["name", "salary"]]

  name   salary
2   王芳  27000.0
4   陈静  23000.0
0   张伟  21000.0
1   李娜  18000.0
6   赵敏  16000.0
3   刘洋  15000.0
7   周强  14000.0
5   杨磊      NaN

## 14. `set_index()` / `reset_index()` — 设置与重置索引

In [17]:
# 将 emp_id 设为索引
indexed = employees.set_index("emp_id")
display(indexed.loc[[3, 5], ["name", "salary"]])   # 用 emp_id 直接取数

# 还原为默认整数索引
indexed.reset_index().head(3)

       name   salary
emp_id
3        王芳  27000.0
5        陈静  23000.0

,emp_id,name,department,age,salary,hire_date,city,gender,annual_salary,senior
0,1,张伟,研发,29,21000.0,2019-03-01,北京,M,252000.0,False
1,2,李娜,市场,34,18000.0,2017-07-15,上海,F,216000.0,False
2,3,王芳,研发,41,27000.0,2015-01-20,北京,F,324000.0,True

## 15. 缺失值检测 — `isnull()` / `notnull()` / `.sum()`

In [18]:
# 每列缺失值数量
print("各列缺失值数量：")
print(employees.isnull().sum())

# 含缺失值的行
print("\n含缺失值的行：")
employees[employees.isnull().any(axis=1)][["name", "department", "salary"]]

各列缺失值数量：
emp_id           0
name             0
department       1
age              0
salary           1
hire_date        0
city             0
gender           0
annual_salary    1
senior           0
dtype: int64

含缺失值的行：

  name department   salary
5   杨磊         研发      NaN
7   周强        NaN  14000.0

## 16. `fillna()` — 填充缺失值

In [19]:
filled = employees.copy()
# 数值列用中位数填充，类别列用众数/固定值填充
filled["salary"] = filled["salary"].fillna(filled["salary"].median())
filled["department"] = filled["department"].fillna("未分配")

filled[["name", "department", "salary"]]

  name department   salary
0   张伟         研发  21000.0
1   李娜         市场  18000.0
2   王芳         研发  27000.0
3   刘洋         销售  15000.0
4   陈静         市场  23000.0
5   杨磊         研发  18000.0
6   赵敏         销售  16000.0
7   周强        未分配  14000.0

## 17. `dropna()` — 删除缺失值

In [20]:
# 删除任何含缺失值的行
print("dropna 后行数：", employees.dropna().shape[0])

# 只在 salary 列缺失时删除
employees.dropna(subset=["salary"]).shape[0]

dropna 后行数： 6

7

## 18. `astype()` — 类型转换

In [21]:
conv = employees.dropna(subset=["salary"]).copy()
# 浮点薪资转为整数；gender 转为 category 类型（更省内存）
conv["salary"] = conv["salary"].astype(int)
conv["gender"] = conv["gender"].astype("category")

print(conv[["salary", "gender"]].dtypes)
conv[["name", "salary", "gender"]].head(3)

salary       int64
gender    category
dtype: object

  name  salary gender
0   张伟   21000      M
1   李娜   18000      F
2   王芳   27000      F

## 19. `to_datetime()` 与 `.dt` 访问器 — 日期处理

In [22]:
employees["hire_date"] = pd.to_datetime(employees["hire_date"])

# 用 .dt 提取年份，并计算工龄
employees["hire_year"] = employees["hire_date"].dt.year
employees["tenure_years"] = 2023 - employees["hire_year"]

employees[["name", "hire_date", "hire_year", "tenure_years"]]

  name  hire_date  hire_year  tenure_years
0   张伟 2019-03-01       2019             4
1   李娜 2017-07-15       2017             6
2   王芳 2015-01-20       2015             8
3   刘洋 2020-09-10       2020             3
4   陈静 2014-05-30       2014             9
5   杨磊 2018-11-05       2018             5
6   赵敏 2016-08-22       2016             7
7   周强 2021-02-14       2021             2

## 20. `value_counts()` — 频数统计

In [23]:
# 各城市的员工数（normalize=True 可得到占比）
print("各城市人数：")
print(employees["city"].value_counts())

print("\n各城市占比：")
employees["city"].value_counts(normalize=True).round(3)

各城市人数：
city
北京    3
上海    2
深圳    2
杭州    1
Name: count, dtype: int64

各城市占比：

city
北京    0.375
上海    0.250
深圳    0.250
杭州    0.125
Name: proportion, dtype: float64

## 21. `unique()` / `nunique()` — 去重值与去重计数

In [24]:
print("出现过的部门:", employees["department"].unique())
print("不同部门数量 (不含 NaN):", employees["department"].nunique())
print("不同城市数量:", employees["city"].nunique())

出现过的部门: ['研发' '市场' '销售' nan]
不同部门数量 (不含 NaN): 3
不同城市数量: 4

## 22. `groupby()` — 分组聚合（最核心的分析操作）

In [25]:
# 各部门的平均薪资与人数
employees.groupby("department")["salary"].mean().round(0)

department
市场    20500.0
研发    24000.0
销售    15500.0
Name: salary, dtype: float64

In [26]:
# 多列分组：城市 × 性别 的平均年龄
employees.groupby(["city", "gender"])["age"].mean().round(1)

city  gender
上海    F         39.5
北京    F         41.0
      M         27.5
杭州    M         31.0
深圳    F         38.0
      M         28.0
Name: age, dtype: float64

## 23. `agg()` — 一次做多种聚合

In [27]:
# 各部门：薪资的均值/最大/最小 + 人数
employees.groupby("department").agg(
    人数=("emp_id", "count"),
    平均薪资=("salary", "mean"),
    最高薪资=("salary", "max"),
    平均年龄=("age", "mean"),
).round(1)

            人数     平均薪资     最高薪资  平均年龄
department
市场           2  20500.0  23000.0  39.5
研发           3  24000.0  27000.0  33.7
销售           2  15500.0  16000.0  33.0

## 24. `apply()` — 应用自定义函数

`apply` 可作用于 Series（逐元素/逐组）或 DataFrame（逐行/逐列）。

In [28]:
# 对 Series：把薪资分档
def pay_level(x):
    if pd.isna(x):
        return "未知"
    if x >= 22000:
        return "高"
    if x >= 16000:
        return "中"
    return "低"

employees["pay_level"] = employees["salary"].apply(pay_level)

# 对 DataFrame 逐行：拼接展示字符串
employees["label"] = employees.apply(
    lambda row: f"{row['name']}({row['city']})", axis=1
)

employees[["name", "salary", "pay_level", "label"]]

  name   salary pay_level   label
0   张伟  21000.0         中  张伟(北京)
1   李娜  18000.0         中  李娜(上海)
2   王芳  27000.0         高  王芳(北京)
3   刘洋  15000.0         低  刘洋(深圳)
4   陈静  23000.0         高  陈静(上海)
5   杨磊      NaN        未知  杨磊(杭州)
6   赵敏  16000.0         中  赵敏(深圳)
7   周强  14000.0         低  周强(北京)

## 25. `map()` / `replace()` — 值映射与替换

In [29]:
# map：用字典把 M/F 映射为中文
employees["gender_cn"] = employees["gender"].map({"M": "男", "F": "女"})

# replace：替换部门名称
employees["department"] = employees["department"].replace({"研发": "研发部", "市场": "市场部"})

employees[["name", "gender", "gender_cn", "department"]]

  name gender gender_cn department
0   张伟      M         男        研发部
1   李娜      F         女        市场部
2   王芳      F         女        研发部
3   刘洋      M         男         销售
4   陈静      F         女        市场部
5   杨磊      M         男        研发部
6   赵敏      F         女         销售
7   周强      M         男        NaN

## 26. `.str` 字符串访问器 — 文本列批量操作

In [30]:
# 标签列转大写、判断是否包含某城市、取长度
demo = sales.copy()
print("product 列加前缀：")
print(("品类-" + sales["product"]).head(3).tolist())

print("\n员工姓名长度：")
print(employees["name"].str.len().tolist())

print("\n姓名是否姓'王':")
print(employees["name"].str.startswith("王").tolist())

product 列加前缀：
['品类-A', '品类-B', '品类-C']

员工姓名长度：
[2, 2, 2, 2, 2, 2, 2, 2]

姓名是否姓'王':
[False, False, True, False, False, False, False, False]

## 27. `merge()` — 表连接（类似 SQL JOIN）

把销售表与员工表按 `emp_id` 关联，给每笔订单补上员工信息。

In [31]:
merged = sales.merge(
    employees[["emp_id", "name", "department", "city"]],
    on="emp_id",
    how="left",          # 左连接：保留所有订单
)
merged.head()

   order_id  emp_id product  quantity  price  order_date name department city
0      1001       1       A         3    199  2023-01-05   张伟        研发部   北京
1      1002       2       B         5     99  2023-01-08   李娜        市场部   上海
2      1003       1       C         2    299  2023-02-11   张伟        研发部   北京
3      1004       4       A         7    199  2023-02-15   刘洋         销售   深圳
4      1005       7       B         1     99  2023-03-01   赵敏         销售   深圳

## 28. `concat()` — 纵向 / 横向拼接

In [32]:
# 纵向拼接：把两个月份的子表上下叠加
jan = sales[sales["order_date"].str.startswith("2023-01")]
feb = sales[sales["order_date"].str.startswith("2023-02")]

combined = pd.concat([jan, feb], ignore_index=True)
print("1 月 + 2 月订单数:", len(combined))
combined

1 月 + 2 月订单数: 4

   order_id  emp_id product  quantity  price  order_date
0      1001       1       A         3    199  2023-01-05
1      1002       2       B         5     99  2023-01-08
2      1003       1       C         2    299  2023-02-11
3      1004       4       A         7    199  2023-02-15

## 29. `pivot_table()` — 透视表

行=员工、列=产品，值=销售额合计，快速得到二维汇总。

In [33]:
sales["amount"] = sales["quantity"] * sales["price"]

pivot = sales.pivot_table(
    index="emp_id",
    columns="product",
    values="amount",
    aggfunc="sum",
    fill_value=0,
    margins=True,          # 加总计行/列
)
pivot

product     A     B     C   All
emp_id
1        2388     0   598  2986
2           0   495  1794  2289
3         199     0     0   199
4        2189   495     0  2684
5           0   198     0   198
7           0    99   897   996
All      4776  1287  3289  9352

## 30. `cut()` / `qcut()` — 数值分箱（连续变量离散化）

- `cut`：按**自定义区间**分箱
- `qcut`：按**分位数**等频分箱

In [34]:
# cut：按指定年龄段分组
employees["age_group"] = pd.cut(
    employees["age"],
    bins=[20, 30, 40, 50],
    labels=["20-30", "30-40", "40-50"],
)

# qcut：按薪资三等分（低/中/高）
employees["salary_tier"] = pd.qcut(
    employees["salary"], q=3, labels=["低", "中", "高"]
)

employees[["name", "age", "age_group", "salary", "salary_tier"]]

  name  age age_group   salary salary_tier
0   张伟   29     20-30  21000.0           高
1   李娜   34     30-40  18000.0           中
2   王芳   41     40-50  27000.0           高
3   刘洋   28     20-30  15000.0           低
4   陈静   45     40-50  23000.0           高
5   杨磊   31     30-40      NaN         NaN
6   赵敏   38     30-40  16000.0           低
7   周强   26     20-30  14000.0           低

## 附加：4 个高频补充功能

虽然主清单是 30 个，这里再补充几个日常分析极常用的小工具。

### A1. `duplicated()` / `drop_duplicates()` — 去重

In [35]:
dup_demo = pd.DataFrame({"city": ["北京", "上海", "北京", "深圳", "上海"]})
print("是否重复:", dup_demo["city"].duplicated().tolist())
print("去重后:", dup_demo["city"].drop_duplicates().tolist())

是否重复: [False, False, True, False, True]
去重后: ['北京', '上海', '深圳']

### A2. `crosstab()` — 交叉频数表

In [36]:
# 城市 × 性别 的人数交叉表
pd.crosstab(employees["city"], employees["gender"], margins=True)

gender  F  M  All
city
上海      2  0    2
北京      1  2    3
杭州      0  1    1
深圳      1  1    2
All     4  4    8

### A3. 累计 / 滚动 — `cumsum()` / `rolling()`

In [37]:
ts = sales.sort_values("order_date").copy()
ts["amount"] = ts["quantity"] * ts["price"]
ts["cum_amount"] = ts["amount"].cumsum()                 # 累计销售额
ts["rolling3"] = ts["amount"].rolling(3).mean().round(1) # 3 期移动平均
ts[["order_date", "amount", "cum_amount", "rolling3"]]

    order_date  amount  cum_amount  rolling3
0   2023-01-05     597         597       NaN
1   2023-01-08     495        1092       NaN
2   2023-02-11     598        1690     563.3
3   2023-02-15    1393        3083     828.7
4   2023-03-01      99        3182     696.7
5   2023-03-09     796        3978     762.7
6   2023-03-20    1794        5772     896.3
7   2023-04-02     198        5970     929.3
8   2023-04-18    1791        7761    1261.0
9   2023-05-05     897        8658     962.0
10  2023-05-21     495        9153    1061.0
11  2023-06-01     199        9352     530.3

### A4. `to_csv()` / `read_csv()` — 读写文件

In [38]:
# 写出再读回，验证往返一致
employees.to_csv("employees_demo.csv", index=False, encoding="utf-8-sig")
reloaded = pd.read_csv("employees_demo.csv")
print("写出并读回成功，形状:", reloaded.shape)
reloaded.head(2)

写出并读回成功，形状: (8, 17)

,emp_id,name,department,age,salary,hire_date,city,gender,annual_salary,senior,hire_year,tenure_years,pay_level,label,gender_cn,age_group,salary_tier
0,1,张伟,研发部,29,21000.0,2019-03-01,北京,M,252000.0,False,2019,4,中,张伟(北京),男,20-30,高
1,2,李娜,市场部,34,18000.0,2017-07-15,上海,F,216000.0,False,2017,6,中,李娜(上海),女,30-40,中

---
## 小结

| # | 功能 | 用途 |
|---|------|------|
| 1-4 | head/info/describe/属性 | 快速了解数据 |
| 5-9 | 列选择 / loc / iloc / 布尔筛选 / isin | 取数据子集 |
| 10-14 | 新增列 / drop / rename / sort / 索引 | 整理结构 |
| 15-19 | 缺失值 / astype / 日期 | 数据清洗 |
| 20-26 | value_counts / groupby / agg / apply / map / str | 统计与变换 |
| 27-30 | merge / concat / pivot_table / cut | 合并与汇总 |

掌握这 30 个功能，已能覆盖绝大多数日常数据处理与实证分析的预处理工作。